/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "sync_counter.v:1.1-15.10" *)
module sync_counter(gclk, rst_n, en, count);
  (* force_downto = 32'd1 *)
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "9" *)
  wire [9:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [9:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [9:0] _02_;
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _03_;
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _04_;
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _05_;
  (* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _06_;
  (* src = "sync_counter.v:5.23-5.28" *)
  output [9:0] count;
  reg [9:0] count;
  (* src = "sync_counter.v:4.23-4.25" *)
  input en;
  wire en;
  (* src = "sync_counter.v:2.23-2.27" *)
  input gclk;
  wire gclk;
  (* src = "sync_counter.v:3.23-3.28" *)
  input rst_n;
  wire rst_n;
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[8] <= 1'h0;
    else if (en) count[8] <= _02_[8];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[9] <= 1'h0;
    else if (en) count[9] <= _02_[9];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[0] <= 1'h0;
    else if (en) count[0] <= _01_[0];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[1] <= 1'h0;
    else if (en) count[1] <= _02_[1];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[2] <= 1'h0;
    else if (en) count[2] <= _02_[2];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[3] <= 1'h0;
    else if (en) count[3] <= _02_[3];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[4] <= 1'h0;
    else if (en) count[4] <= _02_[4];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[5] <= 1'h0;
    else if (en) count[5] <= _02_[5];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[6] <= 1'h0;
    else if (en) count[6] <= _02_[6];
  (* src = "sync_counter.v:8.5-13.8" *)
  always @(posedge gclk)
    if (!rst_n) count[7] <= 1'h0;
    else if (en) count[7] <= _02_[7];
  assign _01_[0] = ~count[0];
  assign _02_[1] = count[1] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _02_[2] = count[2] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[1];
  assign _02_[3] = count[3] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[2];
  assign _02_[4] = count[4] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[3];
  assign _02_[5] = count[5] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[4];
  assign _02_[6] = count[6] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[5];
  assign _02_[7] = count[7] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[6];
  assign _02_[8] = count[8] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[7];
  assign _02_[9] = count[9] ^(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[8];
  assign _00_[1] = count[1] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _00_[3] = _03_ &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _00_[1];
  assign _00_[7] = _06_ &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _00_[3];
  assign _03_ = count[3] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[2];
  assign _04_ = count[5] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[4];
  assign _05_ = count[7] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[6];
  assign _06_ = _05_ &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _04_;
  assign _00_[5] = _04_ &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[3];
  assign _00_[2] = count[2] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[1];
  assign _00_[4] = count[4] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[3];
  assign _00_[6] = count[6] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[5];
  assign _00_[8] = count[8] &(* src = "sync_counter.v:12.22-12.35|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[7];
  assign _00_[0] = count[0];
  assign _01_[9:1] = count[9:1];
  assign _02_[0] = _01_[0];
endmodule
